name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0
  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.10 # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64 # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          version: 2.1.4 # The version of PDM to install. Leave it as empty to use the latest version from PyPI
          prerelease: true # Allow prerelease versions to be installed
          enable-pep582: true # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: pdm install # Then you can use pdm in the following steps.
      - name: Set pythonpath
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Test with Coverage
        run: poetry run pytest --cov=. --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml
  sonar:
    needs: test
    if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-xml
      - name: Fix coverage file for sonarcloud
        run: sed -i "s/home\/runner\/work\/starlite-hello-world\/app/github\/workspace/g" coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
