name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.10 # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64 # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          version: 2.1.4 # The version of PDM to install. Leave it as empty to use the latest version from PyPI
          prerelease: true # Allow prerelease versions to be installed
          enable-pep582: true # Enable PEP 582 package loading globally
      - run: pdm install -G :all
      - name: Set pythonpath
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - run: black --diff --check $(git ls-files '*.py')
      - run: pylint $(git ls-files '*.py')
      - run: mypy --strict $(git ls-files '*.py')